sudo: false
language: go
go:
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
before_script: # tests need to interact with git
  - git config --global user.email "travis@localhost.com"
  - git config --global user.name "Travis"
